sudo: required
services:
- docker
language: go
go:
- 1.7
script:
- set -e
- export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
- export BASE=$(echo $PWD | sed "s|$GOPATH/src/||")
- export GO_TEST_PACKAGES=$(go list ./... | grep -v vendor | sed "s|$BASE/|./|" )
- go test $GO_TEST_PACKAGES
- goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
before_install:
# - docker login -u $DOCKER_REG_USERNAME -p $DOCKER_REG_PASSWORD $DOCKER_REGISTRY
# - chmod 755 ./docker-push.sh
- go get github.com/mitchellh/gox
- go get -u github.com/tcnksm/ghr
after_success:
- gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
- ghr --username $GITHUB_USER --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
- make builddocker
# - "./docker-push.sh"
