sudo: required
services:
- docker
language: go
go:
- 1.7
script:
- set -e
- export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
- export BASE=$(echo $PWD | sed "s|$GOPATH/src/||")
- export GO_TEST_PACKAGES=$(go list ./... | grep -v vendor | sed "s|$BASE/|./|" )
- go test $GO_TEST_PACKAGES
# - echo "Troubehsooting env encyrpt $GITHUB_TOKEN"
# - env
after_success:
- go get github.com/mitchellh/gox
- go get -u github.com/tcnksm/ghr
- gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
- ghr --username $GITHUB_USER --token $GITHUB_TOKEN --replace --prerelease --debug
  pre-release dist/
- make builddocker
env:
  global:
  - secure: Jqp0HoA4nUbjIl6DdxZC6WWg55pPVg/+cVixqne8D/GGYQmSH8E5y6OiuZFrarUGDkioaWxhmYvHUx4HjEOX2sSjAnMcQCIAb6QO94FqgkJYRJNl5Zwa9BTSl3jjqfMOajzC40mjsn25NAFuC4pGKiA6VycuHuBGdmqRrSE0WenWfRrJj5bh/BIraLD6WRol0a9lkhaxDwJGEBGXygaQODRCcg4d2H/vvFFRFMKCWUzjCJJJ9MczhOoJlieocIR1TUt88xdRekKWFBPM50drPK3uwkwQ5hw1zWyZHzBdbS9jrc7c0/S2L13Nw1Q37lw2O78GI3RsVRvMtFSBK7IT/A2nOTmMSpa0Fljky9X43Zwseuao0WagvS12ClTWJoGIKG+5hUOUgdXrd0EehAnjtAxN+mqgTDwoRBszC7/U3a97BAZLZI14hEEG3MoqyKTqfAoeC0bNVL214xtozytnswkRGgBX9n481i4qhb3zfzcyMg5J4lqDtCy526qJD2j9pKr7Eq+Fl+ub9+lWl+5Jdrw9YiO2KhQIuvsiosQ5HdIb2aB1+8Akg81i9PB+OqZfbKrEB7FWuVvoN/LWH4XhM7yfoHOzFPxsAi6rULpKvzohdc7GtNeWsUZDKROwifCdZw0jq8ruvd9t95dMxLNwpfkKGggWMtliS05rgTOWb3M=
  - secure: ARbIKU7DXjq1k+SqJkO+RaN7E3cIElJSWGV5paq05T9GjE+2zFas6AVaKnT1UwT4ZRd3nEAwlug6NYhp0WlGy5oHpNt9BlOcLgV9GMBt64EZ+FfxE9let/SUA0rzY7XeutdDqNxgpFhiagg9Ern27aPNKkN/ilo+tx959Q7+jBDDOILeL/Asi55fWXishKmzUPrA0z5AzB5X2jOqTdXtJ9uQC1fpAP/TG5hyY9pTpekLLN6rucuYniXVsfFt/AcSbUFt9bl4kZavJNbHPl5JGH2aEiv2+walM9Ty9gkFSIBJgCUrC2nHz00d0126vWA1VovwKhNRNd2s0Yw4TZ2pN/EVXhGsr9v01R+O6y1mWQRQx1ekQ3Ouh6X3fv2gQ4YGOeOVC9JhZkpp5HZBmtr81i4axVxXbmTeYks4jmMzvxlqeZZGS6kQP/BDxeoHzFKLN1eFSjzvOOj4m7sqreicStkSNcQ92UTxnUl0sGzXM7Xov9UjUCBGnmhXqXAnw/JtoS1KW9OsxwAgvVA09OFvkpSKPTdoPLkdPky5zwMEE0mnOJoYe3RzoUotCdcol3yeG8uq30x/zGNkuQbdOI1TFvrqfaRW9634MoQcRd29grnBN0IzgCO5r1n2PF87wMR5vOJOYQVBlLnnJnblZvmP6CrQNF9Jos3+IMMNihOhQ7g=
