sudo: required
services:
- docker
language: golang
script:
- set -e
- export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
- make test
- make builddocker
- docker-push.sh
before_install:
- docker login -u $DOCKER_REG_USERNAME -p $DOCKER_REG_PASSWORD $DOCKER_REGISTRY
- chmod 755 ./docker-push.sh
