sudo: required
services:
- docker
language: go
go:
- 1.7
script:
- set -e
- export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
- export BASE=$(echo $PWD | sed "s|$GOPATH/src/||")
- export GO_TEST_PACKAGES=$(go list ./... | grep -v vendor | sed "s|$BASE/|./|" )
- go test $GO_TEST_PACKAGES
before_install:
- go get github.com/mitchellh/gox
- go get -u github.com/tcnksm/ghr
after_success:
- gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
- ghr --username $GITHUB_USER --token $GITHUB_TOKEN --replace --prerelease --debug
  pre-release dist/
- make builddocker
env:
  global:
  - secure: kZC7A4PABVE8rSHDi85G+irzCwD19UyeBnTVVyBliFbXZyGJNN5B8DkWI/7NmTgP0Pj2I2l7u3PHiDMS/Gl+F4ZZ01qyu+Zblz8WngBUl09xKdC4fXZNL7lGo7peLfNynFZ8NXRF7hp037kKuU+B42pf1lW2+6Lor2NRwZQ/Gyn5Rp/9v3VNzDG0tMPN0xOyCAMlx1SNpKMSz+1JcBK9hyEJrGBpf1MMx8sTOSodRzhG06XyCLece/KXCjG/mdSfeW6jE5beygb8GfN03UWGrX9PrkzoDD4TXFuBCEqUElTlmQTHtMDjXyHo5rRSJdo9CFQbxwxJ99Uc25agbD8Ikzs0Ev+Hc5HQGARDnW/zdwe6w2zX7JVm80KD9pQXoJIVbslXajN42xsvfTSW/3abOfqZ4WapqA4WYtTQCvSJVbOgU56ha7vnOSmlTJrgkP2QvngIUn/7bup9av9EkNbOn5n748JKXnpwE8swnMpY1HqZxGhBre0TT204qcYKp9oz2KtNa60UIyi0g5HLLh8V/gtZiUQKPT2/ABcDSjHYmDT9ids2V6uqS7DLqOQzzWFOfxkANBeqpPEXU+XdjjFGyOZ6/YC6qbsyIkarFTS3B8ihrwndtN4ehXPz61/YZuC9Yknfeu4o97QbIPft5AXr7TH/6tRdOOhhZpfZyBN8aFI=
  - secure: ijtXFZJ26Vk5oF23SktB3YZq6hjPaO+7gOSqiR7IP0+SId9+xW/uLaHlADXt3nURoLxiXeM0TmLPmldGibifH/Cr+alOQHA9YhFhM2L641JsUE+ow1DLznKEwyPFHbY8u1fr6qpTsNxH+FJgQYw7tZr3JujW+2wS10KjFqDyayzGYkNd3olyGH8rf3N/u/lztZJCwKse7Bq7BuDbWuOzs9bv9sHY21HAqMFd0pisepmdnT0nCqVp7rBv1axTKO2oVzV4dfgI5ejyOtGZoYCUjOPBNFclGm4cg53wGY4Sz+Psh4Wg2Nq+BMMR9TbH3vxKtCzO7YjfMebv1wJVvoYmvsgql1rHAn26I9mxAgZEtHQL8sK5QUu8Uf3siwDg6+9T8dBF7IFNo8dLj66IwjfuzDVgWpBXdMJprrKxkuEwTwNWNaCHqG7X1Z68zXOhAEGsJVbHKoYlVO3IrcfXRalgI5ZBG8ynW8XFOJk9mE5lJAJz7rpZIKStZpo78sxKDd5fpArYn23aFeeE2d8QsF+MXB011WT9D2r8CbwJRNcw3gXTXv76d4lIeWWUhpBd3o0/62QVtSWu7FlkRnQhJH2J9LPQvJsaeEiGla4KGfxp6CUe9aj0WAq1tx74n8ovu0EtKo19Sr/Q1JBGiEWbd4NZDJjGcpS2T+jicQ0SAEwxXFc=
