sudo: required
services:
- docker
language: go
go:
- 1.7
script:
- set -e
- export BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
- export BASE=$(echo $PWD | sed "s|$GOPATH/src/||")
- export GO_TEST_PACKAGES=$(go list ./... | grep -v vendor | sed "s|$BASE/|./|" )
- go test $GO_TEST_PACKAGES
after_success:
- go get github.com/mitchellh/gox
- go get -u github.com/tcnksm/ghr
- gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
- ghr --username $GITHUB_USER --token $GITHUB_TOKEN --replace --prerelease --debug
  pre-release dist/
- make builddocker
