FROM golang

# Thanks
ADD Makefile /Makefile
WORKDIR /

ADD . /go/src/github.com/backpackhealth/formterra/ 
ADD vendor /vendor
RUN make buildtest

RUN make buildtest
RUN make buildgo
CMD ["/bin/bash"]
