// Code generated by go-bindata.
// sources:
// assets/Makefile
// assets/module_client.tf
// assets/project.tf
// assets/s3.tf
// DO NOT EDIT!

package tfproject

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _assetsMakefile = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x74\x51\xc1\x4e\xdc\x30\x10\x3d\xaf\xbf\x62\x04\x39\x24\x08\xb3\xf7\x45\x51\xb5\xaa\x80\xa2\x96\xb6\x02\x54\xa9\x27\x64\xe2\x09\x6b\x35\xb1\xd3\xb1\xb3\xd5\x0a\xf1\xef\x1d\x3b\x81\x4d\x96\xf6\x38\x33\xef\xbd\x79\xf3\xe6\x18\xae\xd0\x22\xa9\x80\x1a\x6e\xd4\x2f\xac\x4d\x83\xa7\x50\x11\xa6\xce\xe3\x0e\x9e\x9f\xb7\x48\xde\x38\xfb\xf2\x22\xc4\x31\x5c\xd7\x10\x36\x48\x08\xc6\x83\x82\x80\x44\xaa\x76\xd4\x9e\x85\x7a\xab\xc8\x33\xa0\xf7\xc8\x08\x15\x40\xf9\xfd\x18\x8c\xed\xfa\xc0\x53\x5e\xc4\xec\x08\xb0\xa0\xb1\x43\xab\xc1\x59\x40\xbb\x35\xe4\x6c\x8b\x36\x00\xcb\x18\xf5\xd8\xa0\x07\x47\x51\x8c\x46\xee\xfd\xe5\xc3\x8f\xf5\xed\xc3\xfa\xf6\xea\x0e\x3e\x94\xc2\xd4\x16\x7f\x43\x9e\xe5\x7f\x4c\xa3\x2b\x45\x1a\xb2\x7c\x84\x5c\x5e\x7f\xb9\x28\x8a\xd3\x62\x4a\x29\xa5\x64\x61\x19\xaf\x2b\xe7\x40\xc1\x1e\x4c\x2d\x22\x38\xd6\x77\xe5\x44\xf2\x84\xcf\x2a\x84\x38\xfb\xfe\xe9\xdb\xd7\x9f\x2b\xe8\x1a\x76\x4d\x58\x13\xfa\x0d\xa8\xae\x6b\x76\x50\x35\xc8\x3d\x86\xbc\x9d\xba\x1a\x8c\x24\xad\x42\x2c\xf6\x11\x3c\x61\x00\x29\xfb\x4e\x73\xb2\x62\xc1\x2d\x30\x7c\x1a\x64\x59\xde\x78\xd8\xf3\x97\xad\xd3\x3d\x9f\xbf\x3c\x59\xbe\xfe\xa3\x38\x07\xed\xc0\x94\x0c\xd5\x86\xac\x6a\x91\x59\x86\xbb\x58\x6d\x1c\x1c\xdd\xd3\xce\xd8\x27\x68\x19\x3d\x08\x9a\xa3\xf3\xa1\x92\x1f\x63\x15\xd9\x16\x85\x88\xf6\x67\xee\x26\x5b\xa7\x46\xd3\x99\xd2\xf5\x61\xf6\xde\xd4\x7d\x8b\x2e\x66\xca\xc9\x8c\x61\xac\xa6\xf4\xd7\x80\x0e\xb1\x87\x62\xff\xb7\x92\xe5\x37\xeb\xcf\x17\x45\x32\x22\x44\x0a\x7a\xf5\xce\xcb\x74\xe5\xf0\x8b\x77\x08\x91\xbe\x33\x33\xa7\xd1\x07\x72\x3b\x90\x5c\x55\x78\xe8\x71\xc1\x08\x49\xf5\xcc\xcc\xd8\x9a\x8a\xfb\x90\x5e\xf8\x8f\xc9\xb0\x56\xfc\x0d\x00\x00\xff\xff\xc3\x04\xd6\x2e\x55\x03\x00\x00")

func assetsMakefileBytes() ([]byte, error) {
	return bindataRead(
		_assetsMakefile,
		"assets/Makefile",
	)
}

func assetsMakefile() (*asset, error) {
	bytes, err := assetsMakefileBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "assets/Makefile", size: 853, mode: os.FileMode(420), modTime: time.Unix(1479000212, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _assetsModule_clientTf = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x4c\x8e\xc1\xca\xc2\x30\x10\x84\xef\x7d\x8a\x21\xf4\xbf\xfd\xf4\x01\x84\x9e\xc5\x8b\x88\xa0\xf7\xd5\x6e\x6b\xb0\x49\x43\x92\x1e\x64\xc9\xbb\xbb\x35\x08\xde\x86\x9d\xe1\xfb\x56\x04\x03\x8f\xd6\x33\x8c\x5b\x86\x75\x66\x53\x4a\xd3\xd4\x08\x23\xd2\x1d\xc9\x71\x29\x06\xd2\x00\x69\x59\xe3\x9d\xd1\x7f\x8a\xcb\xf9\xa0\x77\xbd\x2a\x22\x92\x9f\x18\xed\x93\x5f\xff\x68\x1d\x85\x60\xfd\x84\x5d\x8f\x6e\xcf\xf9\x4a\xd1\xd2\x6d\xe6\x04\x25\x6f\xeb\xef\xa0\xd3\xa6\xd2\x2b\x31\x44\xeb\xf3\x08\xd3\xca\x5f\x52\xe1\xef\xec\x44\xf9\xa1\x32\x35\xb1\x1f\x36\x8e\xfe\x28\xa2\x59\xe3\x3b\x00\x00\xff\xff\x66\xe6\x33\x70\xc2\x00\x00\x00")

func assetsModule_clientTfBytes() ([]byte, error) {
	return bindataRead(
		_assetsModule_clientTf,
		"assets/module_client.tf",
	)
}

func assetsModule_clientTf() (*asset, error) {
	bytes, err := assetsModule_clientTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "assets/module_client.tf", size: 194, mode: os.FileMode(420), modTime: time.Unix(1478995269, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _assetsProjectTf = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x5c\x8c\x31\x0b\xc2\x30\x10\x85\xf7\xfe\x8a\x47\xe9\x28\xed\x2e\x38\x38\x39\x29\x4e\xee\x57\x73\x48\x31\x49\x25\x89\x85\x72\xdc\x7f\xf7\xa2\x38\xe8\x4d\xc7\x7b\xdf\xfb\x1a\x11\x24\x8a\x37\x46\x77\xe7\x75\x83\x6e\xa1\x84\xed\x0e\xfd\x81\xcb\xde\xfb\x0b\xa5\xac\xda\x58\x38\xd1\xe8\x19\xad\x48\x25\x7a\xcb\x4f\x14\x58\xb5\x85\x40\xab\x84\xa3\x83\x91\xf5\xfe\x95\x61\x76\x4f\xdb\x56\xeb\xf1\xfd\xe6\x4a\x8a\x14\x0e\x0f\x4f\xc5\xac\x1f\xa2\xfd\xa2\xfa\x6b\x1c\x06\x9c\x93\x15\x57\x76\x18\x57\x88\x2c\x9c\xf2\x34\x47\x2b\x5f\x01\x00\x00\xff\xff\xfb\x9d\x54\x2a\xbf\x00\x00\x00")

func assetsProjectTfBytes() ([]byte, error) {
	return bindataRead(
		_assetsProjectTf,
		"assets/project.tf",
	)
}

func assetsProjectTf() (*asset, error) {
	bytes, err := assetsProjectTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "assets/project.tf", size: 191, mode: os.FileMode(420), modTime: time.Unix(1478995269, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _assetsS3Tf = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xa4\x53\x5d\x6b\x14\x31\x14\x7d\x9f\x5f\x71\x09\x82\xb0\x0f\xbb\x85\x82\xe0\x43\x1f\x56\x47\xa5\x20\x2d\xd4\xea\x6b\xb8\xcd\xdc\x19\xc3\xa6\xc9\x78\x93\xac\x2d\x43\xfe\xbb\xc9\x7c\xd4\x5d\x29\xba\xd2\xfb\x94\x9c\x39\x1f\x37\x70\xa6\xaa\x98\xbc\x8b\xac\x08\x04\xfe\xf4\xd2\x9f\xcb\xbb\xa8\x76\x14\x04\x88\x86\x5a\x8c\x26\x9f\x86\x0a\xf2\x4c\x38\x5c\x80\x18\x86\xf5\xbb\xf1\x72\x85\xf7\x94\xd2\x26\xdf\x3f\xfe\x68\x6c\x4a\x62\x24\xa2\x32\x85\xd5\xb3\xde\x63\xa0\x09\x1b\x06\x00\xdd\x82\x75\x01\xd6\x5f\xed\x37\x62\xaf\x9d\xa5\x06\x52\x1a\x3f\x03\xec\x27\x48\xdb\x6e\x8e\x2b\x43\x16\xef\x4c\x66\x5d\x40\xe0\x48\x33\xbc\x28\x36\xab\xd5\x42\x5c\x41\xed\x6c\x78\x0d\x3b\xa2\x1e\x90\x5d\xb4\x0d\xa0\x31\xe0\x4c\xb3\x18\x7b\x68\x1d\x53\xbe\xfc\xd6\xdc\x5e\xd7\xd7\x70\x8f\x3b\x82\xf0\x5d\x7b\x50\xce\xb6\xba\x8b\x5c\x22\x9f\x48\x9b\xf9\x64\x74\x4b\xea\x51\x19\x92\x1c\x0d\x1d\xac\x08\xd0\x33\xb5\xfa\xa1\xbc\x78\x72\xd8\x88\x83\x8f\xcf\xbe\xa0\x8c\x75\x56\x45\x66\xb2\x41\xce\x1b\xca\xc0\x68\xbd\x0e\xf9\x78\xe4\x5f\xa6\xc1\x47\x9f\x3d\xce\xcf\xfe\xc0\x7d\x70\x8c\x1d\x49\x65\xd0\x17\x82\xf8\x72\xbb\xbd\xaa\xb7\x37\xb5\xbc\xdc\x1e\xae\x91\x5e\x9a\xfc\xe6\x9f\xc9\x9f\x3e\x6f\xdf\x5f\x7e\xb8\xf9\x8f\x54\x7a\xe8\x35\xe3\xdf\x52\xdf\x9e\x3d\xe3\x96\xaa\xa5\x51\x64\xc7\x02\x65\xa0\x72\x31\xf4\x31\x80\x98\x4a\x2a\x99\xba\x6c\x3b\x35\x77\x8f\x26\x52\xd9\xf0\xd5\x70\xd4\xf0\xf5\xdc\xef\xf5\x44\xce\xe5\x4d\x4f\x36\xc8\xa7\x8a\x33\xf3\x48\x69\xf3\x2f\x71\xa2\x54\x37\xa3\xf2\x57\x00\x00\x00\xff\xff\xf7\xb8\x8a\x56\x83\x03\x00\x00")

func assetsS3TfBytes() ([]byte, error) {
	return bindataRead(
		_assetsS3Tf,
		"assets/s3.tf",
	)
}

func assetsS3Tf() (*asset, error) {
	bytes, err := assetsS3TfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "assets/s3.tf", size: 899, mode: os.FileMode(420), modTime: time.Unix(1472504225, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"assets/Makefile": assetsMakefile,
	"assets/module_client.tf": assetsModule_clientTf,
	"assets/project.tf": assetsProjectTf,
	"assets/s3.tf": assetsS3Tf,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"assets": &bintree{nil, map[string]*bintree{
		"Makefile": &bintree{assetsMakefile, map[string]*bintree{}},
		"module_client.tf": &bintree{assetsModule_clientTf, map[string]*bintree{}},
		"project.tf": &bintree{assetsProjectTf, map[string]*bintree{}},
		"s3.tf": &bintree{assetsS3Tf, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

